"""added lot of columns in Customers table

Revision ID: 24bae4f2a100
Revises: f98a61b340c9
Create Date: 2023-11-18 18:47:07.601424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24bae4f2a100'
down_revision = 'f98a61b340c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('emergency_person', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('emergency_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('emergency_email', sa.String(length=200), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('emergency_email')
        batch_op.drop_column('emergency_number')
        batch_op.drop_column('emergency_person')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('sex')
        batch_op.drop_column('weight_update')
        batch_op.drop_column('weight')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
