"""added profile pic

Revision ID: 29618cb4fcef
Revises: a0db4cc8e246
Create Date: 2023-12-03 15:02:47.056688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29618cb4fcef'
down_revision = 'a0db4cc8e246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
