"""Added foreign key and other columns in prescriptions

Revision ID: 3580090e0d4f
Revises: 6878928d6f1d
Create Date: 2023-11-21 04:20:29.160638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3580090e0d4f'
down_revision = '6878928d6f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions_pharmacy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instructions_customer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('hospital_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('prescriber_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'doctors', ['prescriber_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['patient_id'], ['id'])
        batch_op.drop_column('doctor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('prescriber_id')
        batch_op.drop_column('hospital_address')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('status')
        batch_op.drop_column('instructions_customer')
        batch_op.drop_column('instructions_pharmacy')

    # ### end Alembic commands ###
