"""added pharmacies table

Revision ID: 6878928d6f1d
Revises: b5b2ba153070
Create Date: 2023-11-20 20:08:40.779381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6878928d6f1d'
down_revision = 'b5b2ba153070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('account_type', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=True),
    sa.Column('store_open', sa.Time(), nullable=True),
    sa.Column('store_close', sa.Time(), nullable=True),
    sa.Column('contact_number', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=500), nullable=True),
    sa.Column('province', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=500), nullable=True),
    sa.Column('brgy', sa.String(length=500), nullable=True),
    sa.Column('st_or_bldg', sa.String(length=500), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
