"""added id to parent class

Revision ID: 8578e6f65af6
Revises: 546ca3ce57a8
Create Date: 2023-11-19 22:10:31.222085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8578e6f65af6'
down_revision = '546ca3ce57a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('middle_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('ptr_number', sa.String(length=120), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_number', sa.String(length=100), nullable=True),
    sa.Column('prc_lic_number', sa.String(length=120), nullable=True),
    sa.Column('s2_lic_number', sa.String(length=120), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
