"""changed customer_id to id

Revision ID: 89693b6399f9
Revises: 715e325402af
Create Date: 2023-11-16 02:14:06.904545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89693b6399f9'
down_revision = '715e325402af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
