"""added birthdate to Doctors

Revision ID: b5b2ba153070
Revises: 8578e6f65af6
Create Date: 2023-11-19 23:45:00.271272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b2ba153070'
down_revision = '8578e6f65af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
